builds:
  - main: main.go
    binary: helm3-monitor
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: archive
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - plugin.yaml
      - completion.yaml
      - scripts/install_plugin.sh
checksum:
  name_template: 'checksums.txt'