name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Shell check
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...
